version: "3.9"

services:
  postgresql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_assets_control
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pitoco@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pitoco"
    ports:
      - "5050:80"
    depends_on:
      - postgresql

volumes:
  pg_data: {}
